# Generates logos_build_info.h — baked into the lgpm binary so `--version`
# can report the release version, this repo's commit (with a "-dirty" marker
# when the checkout is dirty), and the locked commit of each flake input.
# See flake.nix's `buildInfo` for how the values are resolved.
{ pkgs, buildInfo }:

pkgs.writeText "logos_build_info.h" ''
  // Auto-generated by nix/build-info.nix — do not edit.
  #pragma once

  #define LOGOS_BUILD_VERSION "${buildInfo.version}"
  #define LOGOS_BUILD_COMMIT  "${buildInfo.commit}"
  #define LOGOS_BUILD_COMMITS "${pkgs.lib.concatMapStringsSep "\\n" (c: "  ${c.name} ${c.commit}") buildInfo.commits}"
''
