#pragma once

// Version / build-provenance reporting for the lgpm CLI.
//
// The real values come from logos_build_info.h, generated by nix/build-info.nix
// and dropped next to this header at build time (see nix/cli.nix). A plain
// `cmake` build outside nix has no such header — the __has_include guard keeps
// those working, reporting an unversioned dev build.

#include <string>

#if __has_include("logos_build_info.h")
#  include "logos_build_info.h"
#  define LGPM_HAS_BUILD_INFO 1
#else
#  define LGPM_HAS_BUILD_INFO 0
#endif

namespace lgpm_version {

// "portable" for the distributable variant (AppImage / cli-bundle-dir),
// "dev" otherwise. Driven by the LGPM_PORTABLE_BUILD compile define that
// nix/default.nix sets (via -DLGPM_PORTABLE_BUILD=ON) for portable builds.
inline const char* buildType() {
#ifdef LGPM_PORTABLE_BUILD
    return "portable";
#else
    return "dev";
#endif
}

// The release version, or "dev" when unreleased (no VERSION file baked in).
inline std::string version() {
#if LGPM_HAS_BUILD_INFO
    const std::string v = LOGOS_BUILD_VERSION;
    return v.empty() ? "dev" : v;
#else
    return "dev";
#endif
}

// This repo's commit, with a "-dirty" suffix when built from a dirty tree.
inline std::string commit() {
#if LGPM_HAS_BUILD_INFO
    return LOGOS_BUILD_COMMIT;
#else
    return "unknown";
#endif
}

// Full multi-line banner printed by `lgpm --version`. No trailing newline.
inline std::string versionString() {
    std::string out = "lgpm version " + version() + " (" + buildType() + " build)";
#if LGPM_HAS_BUILD_INFO
    out += "\ncommit: " + commit();
    const std::string commits = LOGOS_BUILD_COMMITS;
    if (!commits.empty())
        out += "\ndependency commits:\n" + commits;
#else
    out += "\ncommit: unknown (no build info)";
#endif
    return out;
}

} // namespace lgpm_version
